services:
  - type: web
    name: bot-suivi-telegram
    env: docker
    repo: https://github.com/Thibmymodel/bot-suivi-telegram
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
    autoDeploy: true
